### ISSUE TITLE
Bug / Loader not nice in IE11

### ISSUE THREAD

**Issue by manuelniederberger** [porscheui/porsche-ui-contribution#11]
**Description**  
All loader have in IE11 a slow movement - not as expected the fast spinner

**To Reproduce**  
1. Go to ?p=viewall-molecules-loader in IE11

**Expected behavior**  
A fast moving loader

**Video Attached**  

[2019-04-30_17h44_06.zip](https://github.com/porscheui/porsche-ui-contribution/files/3132016/2019-04-30_17h44_06.zip)

**Comment by o-hook** [comment]
This is the expected (fallback) behaviour in IE11. IE11 does not support CSS path animations and with the given falkback the loader degrades gracefully.
