### ISSUE TITLE
Bug / Disabled Checkbox State

### ISSUE THREAD

**Issue by mgolpashin** [porscheui/porsche-ui-contribution#14]
**Description** 
A disabled Checkbox has a completely different look depending on being checked or unchecked. 

**Expected behavior**
In case the Checkbox is disabled and checked, I expect it to be in grey/disabled color with a squared checked box in front of the title.

**Screenshots**  
![Bildschirmfoto 2019-05-17 um 15 49 03](https://user-images.githubusercontent.com/3465250/57934922-eb679980-78c0-11e9-8a28-c2f77152d464.png)

**Comment by o-hook** [comment]
Fixed colors in disabled/checked state (and also default border color which was too bright):
https://ui.porsche.com/issue/14/react/#/molecules/checkbox
