### ISSUE TITLE
Contribution / Unteren Divider im Header entfernen

### ISSUE THREAD

**Issue by SimonKoller** [porscheui/porsche-ui-contribution#25]
**Scope**  
When im on the home of the finder
where the header is displayed
and i look at the part where the header ends
i dont want to have the last divider that ends the header.

**Comment by o-hook** [comment]
Hi @SimonKoller ,
could you please substantiate this issue? Do you mean the divider underneath the main navigation? And should it be completely removed or does it have to be configurable via a property (because we might need it on the subpages)?

**Comment by SimonKoller** [comment]
Hi @o-hook,
its the last divider of the header element. any other content docks on it. attached you find two screenshots. 
it should be configurable, because you are right, we might need it on other pages.
