### ISSUE TITLE
Bug / Icon Sport Engine looks broken

### ISSUE THREAD

**Issue by stephanschroeter** [porscheui/porsche-ui-contribution#7]
**Description**  
Icon looks wrong see screenshot

**Screenshots**  
<img width="237" alt="Bildschirmfoto 2019-03-29 um 14 49 03" src="https://user-images.githubusercontent.com/30120450/55237225-f5aad700-5231-11e9-9240-c2f9956d5677.png">

**Comment by o-hook** [comment]
This is a known bug in "convertPathData" svgo plugin. It has been fixed by disabling "makeArcs:false".

**Comment by stephanschroeter** [comment]
Fixed in `@porsche/ui-kit-core` v0.18.4
